language: ruby
cache: bundler
before_install:
  - gem install bundler
gemfile: ./Gemfile
script:
  - bundle exec jekyll build
  - bundle exec jekyll algolia
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
rvm:
 - 2.4